---
- name: Configure ACLS
  hosts: routers
  gather_facts: no
  
  vars_files:
    - aclios_var.yml
    
  tasks:
    - name: Configure ACLs IOSXE
      ios_acls:
        config: "{{acl}}"
        state: overridden
      when: ('ios' in ansible_network_os)
