---
- name: Setup management Cisco IOSXE router config
  hosts: routers
  gather_facts: no
  state: override
  
  vars_files:
    - acl_var.yml
    
  tasks:

    - name: Configure ACLs IOSXE
      ios_acls:
        config: "{{acl}}"
      when: ('ios' in ansible_network_os)
      
    - name: Configure ACLs EOS
      eos_acls:
        config: "{{acleos}}"
        state: overridden
      when: ('eos' in ansible_network_os) 
