---
- name: Setup management Cisco IOSXE router config
  hosts: all
  gather_facts: no
  
  vars_files:
    - acl_var.yml
    
  tasks:
    - name: Gather IOSXE router facts
      cisco.ios.facts:
      when: ('ios' in ansible_network_os)
      
    - name: Gather EOS router facts
      arista.eos.facts:
      when: ('eos' in ansible_network_os)

    - name: Configure ACLs IOSXE
      ios_acls:
        config: "{{acl}}"
      when: ('ios' in ansible_network_os)
      
    - name: Configure Loopback interface EOS
      eos_acls:
        config: "{{acl}}"
      when: ('eos' in ansible_network_os) 
