---
- name: Configure ACLS
  hosts: routers
  gather_facts: no
  
  vars_files:
    - acl_var.yml
    
  tasks:
      
    - name: Configure ACLs EOS
      eos_acls:
        config: "{{acleos}}"
        state: replaced
      when: ('eos' in ansible_network_os) 
