---
- name: Gather information from routers
  hosts: all
  gather_facts: no
  
  vars_files:
    - if_var.yml
    - ntp_var.yml
    
  tasks:
    - name: Gather router facts
      cisco.ios.facts:
      
    - name: Display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"    

    - name: configure layer3 interface for ios
      ios_l3_interfaces:
        config: "{{l3_interface}}"

    - name: load ios system properties onto device
      ios_system:
        domain_name: "{{network_domain_name | default(omit, True) }}"
        domain_search: "{{network_domain_search | default(omit, True)}}"
        hostname: "{{network_hostname | default(omit, True)}}"
        lookup_source: "{{network_lookup_source | default(omit, True) }}"
        name_servers: "{{network_name_servers | default(omit, True) }}"

    - assert:
        that:
          - "ntp_server | ipaddr"
        msg: "'ntp_server' must be a valid IPv4 address"

    - name: CONFIGURE NTP
      ios_config:
        lines: "ntp server {{ntp_server}}"

    - name: FETCH NTP STATUS
      ios_command:
        commands:
          - show ntp config
          - show ntp status
      register: ntp_config

    - name: DISPLAY NTP STATUS INTO TERMINAL WINDOW
      debug:
        msg: "{{ntp_config.stdout_lines}}"
