---
- name: Gather information from routers
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather router facts
      cisco.ios.facts:
      
    - name: Display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"
