---
- name: Gather information from routers
  hosts: all
  gather_facts: no
  
  vars_files:
    - if_var.yml
    
  tasks:
    - name: Gather router facts
      cisco.ios.facts:
      
    - name: Display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"    

    - name: configure layer3 interface for ios
      ios_l3_interfaces:
        config: "{{l3_interface}}"
