---
- name: Gather information from routers
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    l3_interface:
      - ipv4:
        - address: "{{interface_ipv4 | default(omit) }}"
        ipv6:
        - address: "{{interface_ipv6 | default(omit) }}"

    
  tasks:
    - name: Gather router facts
      cisco.ios.facts:
      
    - name: Display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"
    
    name: "{{interface_name}}"
    - name: configure layer3 interface for ios
      ios_l3_interfaces:
        config: "{{l3_interface}}"
