---
- name: configure l3 interface
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather router facts
      cisco.ios.facts:
      
    - name: load l3 interface role
      include_role:
        name: ../roles/cisco
