---
- name: load supported platform file or fail
  include: "{{ item }}"
  with_first_found:
  - "{{ ansible_network_os }}.yml"
  - "unsupported_platform.yml"

- name: configure banner
  include_tasks: "{{ ansible_network_os }}.yml"

- name: configure specified vlans
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/{{ ansible_network_os }}.yml"
    - "{{ role_path }}/tasks/unsupported_platform.yml"